import os 

# Smith 
os.system('python3 debug.py smith 1 ./traces/gcc_trace.txt')
os.system('python3 debug.py smith 2 ./traces/gcc_trace.txt')
os.system('python3 debug.py smith 3 ./traces/gcc_trace.txt')
os.system('python3 debug.py smith 4 ./traces/gcc_trace.txt')
os.system('python3 debug.py smith 5 ./traces/gcc_trace.txt')
os.system('python3 debug.py smith 6 ./traces/gcc_trace.txt')

os.system('python3 debug.py smith 1 ./traces/perl_trace.txt')
os.system('python3 debug.py smith 2 ./traces/perl_trace.txt')
os.system('python3 debug.py smith 3 ./traces/perl_trace.txt')
os.system('python3 debug.py smith 4 ./traces/perl_trace.txt')
os.system('python3 debug.py smith 5 ./traces/perl_trace.txt')
os.system('python3 debug.py smith 6 ./traces/perl_trace.txt')

os.system('python3 debug.py smith 1 ./traces/jpeg_trace.txt')
os.system('python3 debug.py smith 2 ./traces/jpeg_trace.txt')
os.system('python3 debug.py smith 3 ./traces/jpeg_trace.txt')
os.system('python3 debug.py smith 4 ./traces/jpeg_trace.txt')
os.system('python3 debug.py smith 5 ./traces/jpeg_trace.txt')
os.system('python3 debug.py smith 6 ./traces/jpeg_trace.txt')

# Bimodal
os.system('python3 debug.py bimodal 7 ./traces/gcc_trace.txt')
os.system('python3 debug.py bimodal 8 ./traces/gcc_trace.txt')
os.system('python3 debug.py bimodal 9 ./traces/gcc_trace.txt')
os.system('python3 debug.py bimodal 10 ./traces/gcc_trace.txt')
os.system('python3 debug.py bimodal 11 ./traces/gcc_trace.txt')
os.system('python3 debug.py bimodal 12 ./traces/gcc_trace.txt')

os.system('python3 debug.py bimodal 7 ./traces/jpeg_trace.txt')
os.system('python3 debug.py bimodal 8 ./traces/jpeg_trace.txt')
os.system('python3 debug.py bimodal 9 ./traces/jpeg_trace.txt')
os.system('python3 debug.py bimodal 10 ./traces/jpeg_trace.txt')
os.system('python3 debug.py bimodal 11 ./traces/jpeg_trace.txt')
os.system('python3 debug.py bimodal 12 ./traces/jpeg_trace.txt')

os.system('python3 debug.py bimodal 7 ./traces/perl_trace.txt')
os.system('python3 debug.py bimodal 8 ./traces/perl_trace.txt')
os.system('python3 debug.py bimodal 9 ./traces/perl_trace.txt')
os.system('python3 debug.py bimodal 10 ./traces/perl_trace.txt')
os.system('python3 debug.py bimodal 11 ./traces/perl_trace.txt')
os.system('python3 debug.py bimodal 12 ./traces/perl_trace.txt')

# Gshare - gcc
os.system('python3 debug.py gshare 7 2 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 7 4 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 7 6 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 8 2 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 8 4 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 8 6 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 8 8 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 9 2 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 9 4 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 9 6 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 9 8 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 10 2 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 10 4 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 10 6 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 10 8 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 10 10 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 11 2 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 11 4 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 11 6 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 11 8 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 11 10 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 12 2 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 12 4 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 12 6 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 12 8 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 12 10 ./traces/gcc_trace.txt')
os.system('python3 debug.py gshare 12 12 ./traces/gcc_trace.txt')

# Gshare - jpeg
os.system('python3 debug.py gshare 7 2 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 7 4 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 7 6 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 8 2 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 8 4 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 8 6 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 8 8 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 9 2 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 9 4 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 9 6 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 9 8 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 10 2 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 10 4 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 10 6 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 10 8 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 10 10 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 11 2 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 11 4 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 11 6 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 11 8 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 11 10 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 12 2 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 12 4 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 12 6 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 12 8 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 12 10 ./traces/jpeg_trace.txt')
os.system('python3 debug.py gshare 12 12 ./traces/jpeg_trace.txt')

# Gshare - perl
os.system('python3 debug.py gshare 7 2 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 7 4 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 7 6 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 8 2 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 8 4 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 8 6 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 8 8 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 9 2 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 9 4 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 9 6 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 9 8 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 10 2 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 10 4 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 10 6 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 10 8 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 10 10 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 11 2 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 11 4 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 11 6 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 11 8 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 11 10 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 12 2 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 12 4 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 12 6 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 12 8 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 12 10 ./traces/perl_trace.txt')
os.system('python3 debug.py gshare 12 12 ./traces/perl_trace.txt')

