import os 

os.system('python3 test.py 16 1024 2 0 0 0 0 ./traces/gcc_trace.txt > ./outputs/out0.txt')
os.system('python3 test.py 16 1024 1 0 0 0 0 ./traces/perl_trace.txt > ./outputs/out1.txt')
os.system('python3 test.py 16 1024 2 0 0 1 0 ./traces/gcc_trace.txt > ./outputs/out2.txt')
os.system('python3 test.py 16 1024 2 8192 4 0 0 ./traces/gcc_trace.txt > ./outputs/out3.txt')
os.system('python3 test.py 16 1024 1 8192 4 0 0 ./traces/go_trace.txt > ./outputs/out4.txt')
os.system('python3 test.py 16 1024 2 8192 4 0 1 ./traces/gcc_trace.txt > ./outputs/out5.txt')
os.system('python3 test.py 16 1024 1 8192 4 0 1 ./traces/compress_trace.txt > ./outputs/out6.txt')

print('Done running all test commands')
print("__________DIFF for File 0__________")
os.system('diff -w ./validation_runs/validation0.txt ./outputs/out0.txt')
print("__________DIFF for File 1__________")
os.system('diff -w ./validation_runs/validation1.txt ./outputs/out1.txt')
print("__________DIFF for File 2__________")
os.system('diff -w ./validation_runs/validation2.txt ./outputs/out2.txt')
print("__________DIFF for File 3__________")
os.system('diff -w ./validation_runs/validation3.txt ./outputs/out3.txt')
print("__________DIFF for File 4__________")
os.system('diff -w ./validation_runs/validation4.txt ./outputs/out4.txt')
print("__________DIFF for File 5__________")
os.system('diff -w ./validation_runs/validation5.txt ./outputs/out5.txt')
print("__________DIFF for File 6__________")
os.system('diff -w ./validation_runs/validation6.txt ./outputs/out6.txt')